### ISSUE TITLE
Production Deploy - Checklist

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C028#132]
# Checklist to remember
## MapStore
Check for geoserver urls in 
- [x] new.json
- [x] localConfig.json 
- [x] incidentiMap.json

Update geoserver authenticationRules in 
- [x] localConfig.json

## GeoServer
- [x] <DATADIR>/monitoring
- [x] <DATADIR>/gwc
- [x] PROXY_BASE_URL
- [x] GeoStore  UserGroup Service username and password
- [x] GeoStore  Role Service username and password
- [x] MapStore AutheKey Service URL

**Comment by tdipisa** [comment]
@MV88 we have to pepare the WAR of MS in the meantime (neext week)

**Comment by MV88** [comment]
[here](http://demo.geo-solutions.it/share/comunebz/) is the mapstore2_prod.war

remember to rename it as mapstore2.war

**Comment by offtherailz** [comment]
For the auth rules we can do some checks (also in dev should be ok) to see if the requests are parsed also as absolute **paths** (e.g. /geoserver) or if they are always parsed with the URL. 
I suggest to use a regex for the <domain name>/geoserver
if needed, a regex for the <ip:port??>/geoserver
and if needed a regex with `^/geoserver` if needed for relative URL

**note:** I hear about some IPs in the URL. I don't know of this use case, but I think they should not be there:

Please verify that the IPs are not provided by the geoserver's capabilities, because saving maps with internal URLs will not make them work outside the internal municipality VPN. So the main access point is the domain name, in any case.
We may need to set the proxy URL in GeoServer (the domain name of sit.comune.... should be visible also in internal network).

**Comment by randomorder** [comment]
Proxy Base URL is set in GeoServer.

I submitted a PR for [prod](https://github.com/geosolutions-it/MapStore2-C028/compare/production...authkey-urlpattern-prod-1?quick_pull=1) and test
