### ISSUE TITLE
Test Deploy v 1.1.4

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C028#80]
Deploy in test for geosolutions-it/ComuneBZ-C028#10

Other needed work:

- [ ] Align the c028 branch on MS2 github to the revision currently used in c028 MS2's project

- [x] Port there the fix provided with geosolutions-it/MapStore2#3214

- [x] Update the MS2's revision in c028 project using the c028 MS2 branch

- [x] Verify ie11 closes issue (requires #74)

- [x] Fix vulnerabilities issues in package.json (requires #79)

**Comment by MV88** [comment]
The branch I used was c028_v114
